Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
